// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Users.Infrastructures.Entities;

public partial class Tuser
{
    public decimal Id { get; set; }

    public Guid Identifier { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int UserType { get; set; }

    public bool Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public byte[] Version { get; set; }

    public virtual TuserCommunication TuserCommunication { get; set; }

    public virtual TuserCredential TuserCredential { get; set; }

    public virtual TuserSetting TuserSetting { get; set; }

    public virtual TuserToken TuserToken { get; set; }

    public virtual TusersOrganization TusersOrganization { get; set; }
}