CREATE TABLE [UserSchema].[TUserCommunications]
(
	[Id] NUMERIC identity(1,1) NOT NULL PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[EmailId] VARCHAR(100) NOT NULL UNIQUE,
	[MobileNumber] VARCHAR(15) NOT NULL UNIQUE,
	[CreatedDate] DATETIME NULL DEFAULT GETDATE(),
	[ModifiedDate] DATETIME NULL DEFAULT GETDATE(),
	[Version] ROWVERSION NULL
	CONSTRAINT [FK_TUserCommunications_TUsers] FOREIGN KEY (UserId) REFERENCES UserSchema.TUsers(Identifier)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
