CREATE TABLE [UserSchema].[TUserTokens]
(
	[Id] NUMERIC identity(1,1) NOT NULL PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	EmailToken UNIQUEIDENTIFIER NULL,
	RefreshToken VARCHAR(MAX) NULL,
	RefreshTokenExpirayTime DATETIME NULL,
	PasswordResetToken UNIQUEIDENTIFIER NULL,
	[CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
	[ModifiedDate] DATETIME NOT NULL DEFAULT GETDATE(),
	[Version] ROWVERSION NULL
	CONSTRAINT [FK_TUserTokens_TUsers] FOREIGN KEY (UserId) REFERENCES UserSchema.TUsers(Identifier)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
