// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Organization.Infrastructures.Entities;

public partial class Torganization
{
    public decimal Id { get; set; }

    public Guid Identifier { get; set; }

    public string Name { get; set; }

    public bool Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public byte[] Version { get; set; }
}